idf_component_register(
    SRCS
        "App_Ui.c"
        "App_UiNav.c"
        "App_UiModel.c"
        "App_UiView.c"
        "components/App_UiComponents.c"
        "pages/App_UiPages.c"
        "pages/App_UiPageHome.c"
        "pages/App_UiPageUsbStatus.c"
        "pages/App_UiPageRuntime.c"
        "port/App_UiPort_Esp32.c"
        "lvgl_app.c"
    INCLUDE_DIRS
        "."
        "include"
    PRIV_REQUIRES
        app_action
    REQUIRES
        lvgl
)
